### ISSUE TITLE
Create display page

### ISSUE THREAD

**Issue by amtang325** [HackGT/match#2]
Create the frontend display page based on the figma design below (no functionality needed for the search bars).
The user cards can be displayed in something like the [SimpleGrid](https://chakra-ui.com/docs/components/simple-grid) in Chakra-UI. The user cards are being worked on in another issue, and so a paragraph or some kind of div can be used as a temporary stand-in until they are ready.

![Screenshot (715)](https://github.com/HackGT/match/assets/45153739/f32d39cd-a954-4654-97f7-eae07584eda7)

**Comment by thaneesh-babu** [comment]
@reesewang25 This [PR](https://github.com/HackGT/match/pull/5) was good for the most part! Except the dropdown's aren't aligned as intended. Also, remove `fontFamily="Roobert"` from the Text component. I know the figma says that but it wasn't a recognized font there, so let's keep it default.

![image](https://github.com/HackGT/match/assets/63804742/80156aa6-c951-495a-ae73-17a4af9e12c3)

**Comment by reesewang25** [comment]
@thaneesh-babu @amtang325 I fixed the name & font issues, but I've been having trouble with the dropdown alignment.

The dropdown alignment is built-in for Menu, MenuButton, and MenuList, and the alignment issue comes from the fact that I am trying use the MenuButton as an Input. If I use MenuButton as a Box, Button, etc, the dropdown is left aligned with the MenuButton.

Since Input is <Input/> and not <Input></Input>, I cannot use <MenuButton as="Input"></MenuButton>.

My last PR has a workaround for creating the MenuButton as a Input, but somehow that's messing with the built-in alignment. Haven't found any fixes online and not sure where to go from here.

**Comment by reesewang25** [comment]
![image](https://github.com/HackGT/match/assets/65859329/8ec91281-8ec3-41c3-8911-a6b7122a1ba4)
If I use `<InputLeftElement>` under `<InputGroup>`, then it does align properly.

**Comment by thaneesh-babu** [comment]
Can we make this a multi select menu? You can look at how we've done in [registration](https://github.com/HackGT/registration2/blob/main/src/components/admin/applications/AllApplicationsTable.tsx) for reference on how we've done it in the past, a lot of the code is reusable here. That should fix your problems, and also filtering is better with multi select.
